name: vmodel
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+111

environment:
  # sdk: ">=2.18.1 <3.0.0"
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  cached_network_image: null
  camera: ^0.10.0+4
  carousel_slider: ^4.2.1
  country_list: ^0.0.5
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^2.0.1
  date_field: ^3.0.1
  desktop_window: ^0.4.0
  either_option: ^2.0.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^3.5.0
  flutter_html: null
  # to erase the flutter native white splash screen and give the app a native splash
  flutter_native_splash: ^2.2.5
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.0.2
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  # # used in getting the screen sized specufic to the device
  # flutter_screenutil: ^5.5.3+2
  #Used to import and display svg in your flutter app
  flutter_svg: ^1.1.5
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.4
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.0
  graphql_flutter: ^5.1.2
  http: null
  image_picker: ^0.8.6
  #used to format date time and some localizations
  intl: null
  intl_phone_field: ^3.1.0
  local_auth: ^2.1.6
  loop_page_view: ^1.2.0
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^7.4.0
  progress_indicators: ^1.0.0
  readmore: ^2.2.0
  rxdart: null
  scroll_bottom_navigation_bar: ^4.0.0
  scroll_date_picker: ^3.6.0
  # for sharing file in flutter
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  iconsax: ^0.0.8
  sizer: ^2.0.15
  switcher: ^1.0.0
  #package used to get date with a custom UI used in shared/vmodel_date_picker
  syncfusion_flutter_datepicker: "20.4.44"
  table_calendar: ^3.0.8
  timelines: ^0.1.0
  url_launcher: ^6.1.11
  video_player: ^2.4.7
  webview_flutter: ^4.2.2
  flutter_portal: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  web_socket_channel: ^2.4.0
  choose_input_chips: ^1.1.3
  animated_check: ^1.0.5
  reorderables: ^0.6.0
  # choose_input_chips:
  #   git:
  #     url: https://github.com/wishwelloklu/choose_input_chips.git
  #     ref: main #branch name
  dm_stepper:
    git:
      url: https://github.com/Weav3r/dm_stepper.git
      ref: vmdl #branch name
      # ref: main #branch name
  like_button: ^2.0.5
  flutter_animated_icons: ^1.0.1
  widget_to_marker:
    ^1.0.4
    # git:
    #   url: https://github.com/Weav3r/choose_input_chips.git
    #   ref: vmd # branch name
  # crop:
  #   git:
  #     url: https://github.com/lukehutch/flutter_crop.git

  google_fonts: ^4.0.4
  photo_manager: ^2.6.0
  #  crop: ^0.5.5
  #  permission_handler: ^10.3.0
  #  custom_image_crop: ^0.0.5
  crop_your_image: ^0.7.5
  cropperx: ^1.1.1
  cross_fade: ^0.3.1
  image_cropper: ^4.0.1
  dart_emoji: ^0.2.0+2
  qr_flutter: ^4.1.0
  flutter_slidable: ^3.0.0
  contacts_service: ^0.6.3
  animations: ^2.0.7
  pinch_zoom_release_unzoom: ^1.0.1
  permission_handler: ^10.4.3
  hooks_riverpod: ^2.3.9
  lottie: ^1.3.0
  geocoding: ^2.1.0
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^20.4.54
  smooth_page_indicator: ^1.1.0
  go_router: ^10.2.0
  gallery_saver: ^2.3.2
  flutter_cache_manager: ^3.3.1
  linear_step_indicator: ^1.0.0+3
  any_link_preview: ^3.0.0
  screenshot: ^2.1.0
  # emoji_picker_flutter: ^1.6.2
  flutter_image_compress: ^2.1.0
  multi_trigger_autocomplete: ^1.0.0
  flutter_parsed_text: ^2.2.1
  flutter_parsed_text_field: ^0.1.10
  # image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # graphql_codegen: ^0.12.0
  faker: ^2.1.0
  riverpod_generator: ^2.2.6
  # riverpod_lint: ^2.0.1
  # custom_lint: ^0.5.2

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logos/new_app_icon.png"
  min_sdk_version: 20
  adaptive_icon_foreground: "assets/logos/new_app_icon.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

  # image_path_ios: "assets/logos/new_app_icon.png"

# flutter_icons:
#   path: ../..

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/print.jpg
    - assets/images/doc/
    - assets/
    - assets/icons/
    - assets/icons_type/
    - assets/images/models/
    # - assets/images/feed_models/
    # - assets/images/portfolio_images/
    # - assets/images/polaroid_images/
    # - assets/images/backgrounds/
    - assets/images/discover_categories/
    - assets/images/photographers/
    - assets/images/userTypes/
    - assets/images/pets/
    - assets/images/doc/
    - assets/images/trendMagazines/
    - assets/images/jobs_market_images/
    - assets/images/review_images/
    - assets/images/create_booking_images/
    - assets/videos/
    - assets/images/business/
    - assets/images/svg_images/
    - assets/images/bg_signup/
    - assets/images/vell_magazine_images/
    - assets/images/map_avatar/
    - assets/images/marketplace_home_banners/
    - .env

  fonts:
    # - family: Avenir
    #   fonts:
    #     - asset: assets/fonts/Avenir/AvenirNextLTPro-Regular.otf
    #     - asset: assets/fonts/Avenir/AvenirNextLTPro-It.otf
    #       style: italic
    #     - asset: assets/fonts/Avenir/AvenirNextLTPro-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/Avenir/AvenirNextLTPro-BoldCn.otf
    #       weight: 600
    #     - asset: assets/fonts/Avenir/AvenirNextLTPro-Demi.otf
    #       weight: 500
    #     - asset: assets/fonts/Avenir/AvenirNextLTPro-DemiCn.otf
    #       weight: 400

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Semibold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 700

    - family: SF
      fonts:
        - asset: assets/fonts/SF/SF-Pro-Text-Bold.otf
          weight: 900
    # - family: Avenir
    #   fonts:
    #     - asset: assets/fonts/AvenirFonts/AvenirNextBold.otf
    #       # weight: 700
    #     - asset: assets/fonts/AvenirFonts/AvenirNextHeavy.otf
    #       # weight: 700
    #     - asset: assets/fonts/AvenirFonts/AvenirNextIt.otf
    #       style: italic
    #       # weight: 700
    #     - asset: assets/fonts/AvenirFonts/AvenirNextLite.otf
    #       # weight: 700
    #     - asset: assets/fonts/AvenirFonts/AvenirNextMedium.otf
    #       # weight: 700
    #     - asset: assets/fonts/AvenirFonts/AvenirNextRegular.otf
    #       # weight: 700
    #     - asset: assets/fonts/AvenirFonts/AvenirNextUltLt.otf
    #       # weight: 700

    # - family: Futura
    #   fonts:
    #     - asset: assets/fonts/futura/Futura-CondensedLight.otf
    #     - asset: assets/fonts/futura/Futura_Book_Italic.ttf
    #       style: italic
    #     - asset: assets/fonts/futura/Futura_Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/futura/Futura_Heavy.ttf
    #       weight: 600
    #     - asset: assets/fonts/futura/futura_medium_bt.ttf
    #       weight: 500
    #     - asset: assets/fonts/futura/Futura_Light.ttf
    #       weight: 400
    #     - asset: assets/fonts/futura/unicode.futurab.ttf
    #       weight: 300
