# name: VModel Workflow 2

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [dev]
#     paths-ignore:
#       - '**/README.md'
#   pull_request:
#     branches: [dev]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   generate-exe:
#     name: 'Generate & Upload Windows'
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: subosito/flutter-action@v2
#       with:
#         flutter-version: "3.3.4"
#         channel: 'stable'
#     - run: flutter config --enable-windows-desktop
#     - run: flutter build windows --release
    
#     - name: Upload EXE
#       uses: actions/upload-artifact@v3
#       with:
#         name: release-exe
#         path: vmodel_builds/*.exe
     